TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += @{device_database_name}.db
DATA += @{device_protocol_name}.proto

#=======================================
include $(TOP)/configure/RULES
